# Generated by Django 4.2.7 on 2023-12-10 02:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chefiapp', '0002_alter_user_date_joined_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('pizzaiolo', 'Pizzaiolo'), ('estafeta', 'Estafeta'), ('caixa', 'Caixa'), ('gerente', 'Gerente')], max_length=20, verbose_name='department'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('management', 'Management'), ('staff', 'Staff')], max_length=20, verbose_name='role'),
        ),
    ]
