# Generated by Django 4.2.7 on 2023-12-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefiapp', '0005_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department_abilities',
            field=models.CharField(blank=True, choices=[('pizzaiolo', 'Pizzaiolo'), ('estafeta', 'Estafeta'), ('caixa', 'Caixa'), ('gerente', 'Gerente')], max_length=20, verbose_name='department abilities'),
        ),
    ]
