# Generated by Django 4.2.7 on 2023-12-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefiapp', '0006_user_department_abilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department_abilities',
        ),
    ]
