# Generated by Django 4.2.7 on 2023-12-13 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefiapp', '0008_department_user_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='department_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
