# Generated by Django 4.2.7 on 2023-12-14 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chefiapp', '0010_alter_department_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCreateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, choices=[('pizzaiolo', 'Pizzaiolo'), ('estafeta', 'Estafeta'), ('caixa', 'Caixa'), ('gerente', 'Gerente')], max_length=20, verbose_name='department')),
                ('activation_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
