# Generated by Django 4.2.7 on 2023-12-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefiapp', '0012_usermonthlyschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermonthlyschedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='usermonthlyschedule',
            name='month',
        ),
        migrations.RemoveField(
            model_name='usermonthlyschedule',
            name='year',
        ),
        migrations.AddField(
            model_name='usermonthlyschedule',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
    ]
