# Generated by Django 4.2.7 on 2023-12-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefiapp', '0014_dailyschedule_monthlyschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyschedule',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=15, verbose_name='month'),
        ),
    ]
