# Generated by Django 4.2.7 on 2023-12-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefiapp', '0015_alter_monthlyschedule_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyschedule',
            name='month',
            field=models.CharField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], max_length=15, verbose_name='month'),
        ),
    ]
