# Generated by Django 4.2.7 on 2023-12-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefiapp', '0016_alter_monthlyschedule_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyschedule',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year'),
        ),
    ]
