# Generated by Django 4.2.7 on 2023-12-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefiapp', '0018_alter_monthlyschedule_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyschedule',
            name='is_dayoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monthlyschedule',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=15, verbose_name='month'),
        ),
    ]
