# Generated by Django 4.2.7 on 2023-12-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefiapp', '0019_dailyschedule_is_dayoff_alter_monthlyschedule_month'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyschedule',
            unique_together={('date', 'monthly_schedule')},
        ),
    ]
